### ISSUE TITLE
Nextjs14,Use agora-rtc-sdk-ng will report an error: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by BikeF** [AgoraIO/agora-rtc-web#6]
### AgoraRTC SDK version

4.20.0

### Fail Rate

100%

### Link to minimal reproduction

https://github.com/BikeF/test-agora-rtc-sdk-ng.git

### Steps to reproduce

 1. npm install
 2. npm run dev
 3. open the page, You will find that the console reports an error:

```
   ⨯ ReferenceError: window is not defined
    at __webpack_require__ (C:\Users\fanfa\Documents\test-agora-rtc-sdk-ng\.next\server\webpack-runtime.js:33:43)
    at eval (./src/app/page.tsx:8:74)
    at (ssr)/./src/app/page.tsx (C:\Users\fanfa\Documents\test-agora-rtc-sdk-ng\.next\server\app\page.js:129:1)
    at Object.__webpack_require__ [as require] (C:\Users\fanfa\Documents\test-agora-rtc-sdk-ng\.next\server\webpack-runtime.js:33:43)
digest: "942138213"
```

### What is expected?

the module file is AgoraRTC_N-production.js,simple code:
```
!function (e, t) {
  if ("object" === typeof exports && "undefined" !== typeof module) {
      module.exports = t();
  } else if ("function" === typeof define && define.amd) {

    define(t);
  } else {
    e = "undefined" !== typeof globalThis ? globalThis : e || self;
    e.AgoraRTC = t();
  }
}(this, (function () {
```

### What is actually happening?

npm run dev    will report an error, but it will not affect the use.
npm run build    will report an error and cause packaging failure.
I should be able to avoid reporting errors by importing synchronously, but I don't want to do so.

### System Info

```shell
nextjs14
```

**Comment by guoxianzhe** [comment]
@BikeF In nextjs usage, you can check https://github.com/AgoraIO-Extensions/agora-rtc-react/issues/181#issuecomment-1886586029

**Comment by andriy-baranskyy** [comment]
Hey there,

This is a classic Next.js SSR issue - `agora-rtc-sdk-ng` expects browser globals like `window`, but Next.js renders components on the server first.

Some ideas worth a try:

**Option 1: Dynamic Import (Recommended)**
```typescript
'use client'; // If using App Router

import dynamic from 'next/dynamic';

const AgoraComponent = dynamic(
  () => import('../components/AgoraVideoCall'),
  { ssr: false } // Disable server-side rendering
);

export default function Page() {
  return <AgoraComponent />;
}
```

**Option 2: Conditional Initialization**
```typescript
useEffect(() => {
  if (typeof window !== 'undefined') {
    import('agora-rtc-sdk-ng').then((AgoraRTC) => {
      // Initialize Agora here
    });
  }
}, []);
```

**Option 3: next.config.js Exclusion**
```javascript
module.exports = {
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.resolve.fallback = {
        ...config.resolve.fallback,
        fs: false,
        net: false,
        tls: false,
      };
    }
    return config;
  },
};
```

**Long-term Consideration:**

If you're building a heavily SSR-dependent Next.js app, you might want WebRTC SDKs designed with SSR in mind. Some alternatives handle this more gracefully (LiveSwitch, Daily.co have better Next.js compatibility out of the box).

**Full disclosure:** I work for LiveSwitch, but the fixes above should work for Agora. The dynamic import approach is typically the cleanest solution.

Hope this helps! Let me know if you hit any other issues.
